### ISSUE TITLE
Basker should follow when scrolling.

### ISSUE THREAD

**Issue by OlofHaglund** [MammasKallare/mKassa-gui#2]

**Comment by PhantomOverride** [comment]
Om listan är statiskt fäst på skärmen så måste man se till så listan får en egen scroll-bar. Annars kan produkter i varukorgen visas "utanför" skärmen. Vet inte om koden ligger nånstans, men att fästa listan är typ en ändring i CSS:en tror jag. Att få en intern scroll-grej är nog inte så svårt det heller, men det kikade jag aldrig på när vi labbade.
