### ISSUE TITLE
Allow to add new product

### ISSUE THREAD

**Issue by OlofHaglund** [MammasKallare/mKassa-gui#5]
Allow to fill all fields for adding new products instead of having to add an empty product and then change all fields.

**Comment by PhantomOverride** [comment]
Om jag inte missminner mig så behöver du i FE tillåta att du öppnar upp modifiering av ett hitte-på-objekt av typen produkt. Backend borde godta det i POST-requesten för create. Men i värsta fall får du väl från FE skicka in en POST och en PUT annars.
