### ISSUE TITLE
Improve GUI design

### ISSUE THREAD

**Issue by OlofHaglund** [MammasKallare/mKassa-gui#7]

**Comment by PhantomOverride** [comment]
Kör hårt. Förslagsvis radar du upp lite målkriterier så det finns något att mäta mot. Typ, ska UI:t aldrig användas på en surfplatta igen finns det en del grejjer man kan göra om direkt. Ska det gå att köra på en mobiltelefon med iZettle så finns andra kriteriet, etc.
